// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace mm
{
	public partial class MyViewControllerr : UIViewController
	{
		public MyViewControllerr (IntPtr handle) : base (handle)
		{
		}
		 public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            Console.WriteLine("Loadeder");
           
            
            // Perform any additional setup after loading the view, typically from a nib.
        }

        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();
            // Release any cached data, images, etc that aren't in use.
        }
       
	}
}
