// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using MapKit;
using UIKit;
using CoreLocation;
using Xamarin.Essentials;

namespace mm
{
	public partial class PopUpView : UIViewController
	{
        public double myLat;
        public double myLong;
        public PopUpView (IntPtr handle) : base (handle)
		{
		}
        
        
        MKMapView map;
       
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
          
            
            map = new MKMapView(UIScreen.MainScreen.Bounds);
            CLLocationCoordinate2D mapCenter = new CLLocationCoordinate2D(myLat, myLong);
            MKCoordinateRegion mapRegion = MKCoordinateRegion.FromDistance(mapCenter, 100, 100);
            map.CenterCoordinate = mapCenter;
            map.Region = mapRegion;
            map.MapType = MKMapType.Standard;
            map.ZoomEnabled = false;
            map.ScrollEnabled = false;
            map.AddAnnotations(new ClockInLocation("Clock In Location", mapCenter));
            View.Add(map);



            // Perform any additional setup after loading the view, typically from a nib.
        }

        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();
            // Release any cached data, images, etc that aren't in use.
        }
    }
}
